//
//  HomeInteractor.swift
//  CleanSwift
//
//  Created by Johnny Sousa on 26/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func fetchHttps(request: Home.Fetch.Request)
    func didSelectHttp(request: Home.SelectHttp.Request)
}

protocol HomeDataStore {
    var statusCodes: [HTTPStatusCode]? { get set }
    var selectedStatusCode: HTTPStatusCode? { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    
    var statusCodes: [HTTPStatusCode]?
    var selectedStatusCode: HTTPStatusCode?
    
    var presenter: HomePresentationLogic?
    
    // MARK: Do something
    func fetchHttps(request: Home.Fetch.Request) {
        let response = Home.Fetch.Response(
            httpStatusCodes: HTTPStatusCode.allCases
        )
        
        statusCodes = response.httpStatusCodes
        
        presenter?.presentSomething(response: response)
    }
    
    func didSelectHttp(request: Home.SelectHttp.Request) {
        let response = Home.SelectHttp.Response()
        
        selectedStatusCode = request.httpStatusCode
        
        presenter?.presentSelectCode(response: response)
    }
}
