//
//  HomeModels.swift
//  CleanSwift
//
//  Created by Johnny Sousa on 26/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    
    enum Request {
        case fetchHttpItems
        case selectHttp(item: HTTPStatusCode)
    }
    
    enum Response {
        case dataHttpItems(items: [HTTPStatusCode])
        case errorFetchHttpItems(error: Error)
        
        case selectHttp(item: HTTPStatusCode)
    }
    
    enum ViewModel {
        case httpItems(items: [HTTPItemProtocol])
        case errorFetchHttpItems(message: String)
        
        case selectHttp(item: HTTPStatusCode)
    }
}
