//
//  HomeWorker.swift
//  CleanSwift
//
//  Created by Johnny Sousa on 26/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeWorkerLogic {
    typealias completionFetchHttpItems = (Result<[HTTPStatusCode], Error>) -> ()
    
    func fetchHttpItems(completion: @escaping completionFetchHttpItems)
}

class HomeWorker: HomeWorkerLogic {
    
    func fetchHttpItems(completion: @escaping completionFetchHttpItems) {
        let httpItems = HTTPStatusCode.allCases
        
        completion(.success(httpItems))
    }
}
