//
//  HomeRouter.swift
//  CleanSwift
//
//  Created by Johnny Sousa on 26/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingLogic {
    func routeToHttp(item: HTTPStatusCode)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: HomeRoutingLogic, HomeDataPassing {
    
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    func routeToHttp(item: HTTPStatusCode) {
        let httpViewController = HTTPDogViewController()
        
        httpViewController.router?.dataStore?.httpStatusCode = item

        viewController?.navigationController?.pushViewController(httpViewController, animated: true)
    }
}
