//
//  HTTPModels.swift
//  CleanSwift
//
//  Created by Johnny Sousa on 30/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum HTTPDog {
    
    enum Request {
        case fetchHttpDogItem(item: HTTPStatusCode)
    }
    
    enum Response {
        case dataHttpDogItem(item: HTTPDogItemProtocol)
    }
    
    enum ViewModel {
        case httpDogItem(item: HTTPDogItemView)
    }
}
